version: '3'
services:
  simulator:
    build: simulator
    ports:
      - 5112:5112
    tty: true
  websockets:
    build: websockets
    environment:
      - EV3DEV_RPC_HOST=10.244.106.37
    ports:
      - 8001:8001
  frontend:
    build: frontend
    environment:
      - WEBSOCKET_URL=ws://localhost:8001
      - VIDEO_URL=http://192.168.0.138:8080/video
    ports:
      - 8080:8080
