version: '3'
services:
  simulator:
    build: simulator
    ports:
      - 5112:5112
    tty: true
  websockets:
    build: websockets
    environment:
      - EV3DEV_RPC_HOST=10.42.0.3
    ports:
      - 8001:8001
  frontend:
    build: frontend
    environment:
      - WEBSOCKET_URL=ws://localhost:8001
    ports:
      - 8080:8080
    depends_on:
      - websockets
